/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Resource {
  $id?: string;
  $schema?: string;
  type?: "object";
  properties?: {
    type?: "object";
    patternProperties?: {
      [k: string]: unknown;
    };
    minProperties?: 1;
    required?: [];
    [k: string]: unknown;
  };
  required?: ["name"];
  anyOf?: [{required: ["properties"]}, {required: ["relations"]}];
  [k: string]: unknown;
}
